version: '3.4'

networks:
  cors_dev:
    external: true

services:
  db:
    image: mysql:8
    working_dir: /application
    container_name: webcare_database
    networks:
      - cors_dev
    volumes:
      - webcare-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  php:
    image: pimcore/pimcore:PHP8.0-apache
    container_name: webcare_php
    networks:
      - cors_dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.webcare.rule=Host(`webcare.localhost`)
      - traefik.http.routers.webcare.entrypoints=cors_dev
      - traefik.http.routers.webcare.tls=true
      - traefik.http.services.webcare.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    volumes:
      - .:/var/www/html:cached
    depends_on:
     - db

  php-debug:
    image: pimcore/pimcore:PHP8.0-apache-debug
    container_name: webcare_php-debug
    networks:
      - cors_dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.webcare_debug.rule=Host(`webcare.localhost`)
      - traefik.http.routers.webcare_debug.entrypoints=cors_dev_debug
      - traefik.http.routers.webcare_debug.tls=true
      - traefik.http.services.webcare_debug.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - db
    environment:
      - PHP_DEBUG=1
      - PHP_IDE_CONFIG="serverName=localhost"

volumes:
  webcare-database:
